
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "
          flake8 &&
          pytest -v -s --durations=0 --cov=. &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          python manage.py initial_data &&
          daphne -b 0.0.0.0 -p 8000 settings.asgi:application"
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - pgs_database

  pgs_database:
    image: postgres:15
    restart: always
    container_name: pro_gaming_software
    volumes:
      - pgs_backend_database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pgs_database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "54322:5432"

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgs_backend_database:
