# Generated by Django 5.1.5 on 2025-01-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default=(('low', 'Low'), ('medium', 'Medium'), ('high', 'High')), max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'In Progress'), ('completed', 'Completed')], default=(('new', 'New'), ('pending', 'In Progress'), ('completed', 'Completed')), max_length=20),
        ),
    ]
